name: Docker Image CI

on:
  push:
    branches: [ feature/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - 
      name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    -
      name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: didrikeilertsen/getting-started:test
    -
      name: Raise a Pull Request
      id: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: master
        github_token: ${{ secrets.GH_TOKEN }}