name: Build, Test, and Raise Pull Request
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          
#           test
          
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: flask-app-gitops/ci/flask-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
     
     -
        name: Build the Docker image
        id: build
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER  }}/flask-app-gitops          
          


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Build the Docker image
#       id: build
#       run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER  }}/flask-app-gitops
#     - name: Raise a Pull Request
#       id: pull-request
#       uses: repo-sync/pull-request@v2
#       with:
#         destination_branch: master
#         github_token: ${{ secrets.GH_TOKEN }}
