name: Docker Image CI

on:
  push:
    branches: [ feature/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - 
      name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    -
      name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: didrikeilertsen/getting-started:test

    -
      name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        destination_branch: ${{ github.event.repository.default_branch }}
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"
#        pr_reviewer: "didrikeilertsen"
#        pr_assignee: "didrikeilertsen"


#    -
#      name: Raise a Pull Request
#      id: pull-request
#      uses: repo-sync/pull-request@v2
#      with:
#        destination_branch: origin/master
#        github_token: ${{ secrets.GH_TOKEN }}

